version: '3.5'

networks:
  zinnet:
    driver: bridge

services:
  zinco: #zinc_observe service
    image: public.ecr.aws/zinclabs/zincobserve:latest
    environment:
      - TZ=Asia/Shanghai
      - ZO_DATA_DIR="/data"
      - ZO_ROOT_USER_EMAIL=euraxluo@outlook.com
      - ZO_ROOT_USER_PASSWORD=123456
    ports:
      - "5080:5080"
    volumes:
      - ./data:/data
    networks:
      - zinnet
    restart: always